version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME}_app
    command:
      - "python"
      - "loader.py"

networks:
  default:
    external: true
    name: ${PROJECT_NAME}_network
