version: "3.7"

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME}_postgres
    command:
      - "postgres"
      - "-c"
      - "shared_preload_libraries=pg_cron"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${DWH_USER}
      POSTGRES_PASSWORD: ${DWH_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - /var/lib/postgresql/data
      - ./postgres/import-export:/import-export
      - ./postgres/dumps:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"

  pgadmin:
    container_name: ${PROJECT_NAME}_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"

networks:
  default:
    name: ${PROJECT_NAME}_network
