checkpoint list:
	great_expectations checkpoint list

checkpoint new:
	great_expectations checkpoint new organizaciones.mincyt

datasource:
	great_expectations datasource

datasource-list:
	great_expectations datasource list
datasource-new:
	great_expectations datasource new

docs:
	great_expectations docs
docs-build:
	great_expectations docs build 
docs-build-nelp:
	great_expectations docs build --help
doc-list:
	great_expectations docs list

help:
	great_expectations --help

init:
	great_expectations init

suite:
	great_expectations suite 

suite-delete:
	great_expectations suite delete

suite-edit:
	great_expectations suite edit -nj -p

# great_expectations suite edit [fuente] -nj -br batch-request-parameters.json 

suite-list:
	great_expectations suite list
suite-new:
	great_expectations suite new -nj

